model_list:
  - model_name: openai-default
    litellm_params:
      model: os.environ/OPENAI_MODEL
      api_key: os.environ/OPENAI_API_KEY

  - model_name: anthropic-default
    litellm_params:
      model: os.environ/ANTHROPIC_MODEL
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: gemini-default
    litellm_params:
      model: os.environ/GEMINI_MODEL
      api_key: os.environ/GEMINI_API_KEY

  - model_name: xai-default
    litellm_params:
      model: os.environ/XAI_MODEL
      api_key: os.environ/XAI_API_KEY

  - model_name: local-default
    litellm_params:
      model: os.environ/LOCAL_MODEL
      api_base: os.environ/LOCAL_OPENAI_BASE_URL
      api_key: os.environ/LOCAL_OPENAI_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
